image: node:10.4.1-alpine

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - yarn install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
