image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - "sed -i 's|^url:.*$|url: https://goodevilgeniusorg.gitlab.io|' _config.yml"
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
