image: node:10.4.1-alpine

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - yarn install
  - "sed -i 's|^url:.*$|url: https://goodevilgeniusorg.gitlab.io|' _config.yml"
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
