image: node:12.8-alpine

before_script:
  - apk add --no-cache make
  - make deps

pages:
  cache:
    paths:
    - node_modules/

  script:
  - make build
  artifacts:
    paths:
    - public
  only:
  - master
