name: "Dan's Musings"
url: http://goodevilgenius.org/
description: My thoughts and observations
timezone: America/Chicago

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/254662

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Includes an icon in the footer for each username you enter
author:
  name: Dan Jones
  from: Texas, USA
  email: 
  facebook: danjones
  flickr: goodevilgenius
  github: goodevilgenius
  instagram: goodevilgenius
  linkedin: danjones000
  rss: http://goodevilgenius.org/feed.xml # just type anything here for a working RSS icon
  twitter: goodevilgenius
  stackoverflow: users/367461/dan-jones # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DanJones000 # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus: danspile

baseurl: ""

permalink: /:year/:month/:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Makefile
